name: "➕ Request addition of a new project"
description: Request the addition of a new project to the install.erdos.one registry
title: "➕ [PROJECT REQUEST] - <title>"
labels: [
  "enhancement"
]
body:
  - type: input
    id: project_name
    attributes:
      label: "Project Name"
      description: Name of the requested project to add
      placeholder: "Project name (i.e. Homebrew)"
    validations:
      required: true
  - type: input
    id: project_url
    attributes:
      label: "Project URL"
      description: Homepage of project to add
      placeholder: "Project URL (i.e. https://brew.sh)"
    validations:
      required: true
  - type: input
    id: install_script
    attributes:
      label: "Project Install Script"
      description: Plain text install script URL
      placeholder: "Install script (i.e. https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    validations:
      required: true
  - type: input
    id: uninstall_script
    attributes:
      label: "Project Uninstall Script"
      description: Plain text uninstall script URL
      placeholder: "Uninstall script (i.e. https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
    validations:
      required: true
  - type: input
    id: shell_name
    attributes:
      label: "Shell name"
      description: Name of shell to use for [un]install
      placeholder: "Shell name (i.e. bash, sh, etc.)"
    validations:
      required: true
  - type: textarea
    id: additional_comments
    attributes:
      label: "Additional Comments"
      description: Please provide any additional comments, if necessary
      placeholder: Comments on project request
    validations:
      required: false